# Uncomment the next line to define a global platform for your project
# platform :ios, 15.0'

target 'CostaRicaRaon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CostaRicaRaon
  
  pod 'RealmSwift'
  pod 'SwiftGen'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'SDWebImageSVGKitPlugin'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FlexibleModelProtocol'
  pod "PromiseKit"
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Gifu'
  pod 'CocoaLumberjack'
  pod 'Then'
  pod 'Moya'
  pod 'ReactorKit'
  
  target 'CostaRicaRaonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CostaRicaRaonUITests' do
    # Pods for testing
  end

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0' # 원하는 최소 버전
      end
    end
end
